name: Depaloy app

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Upgrade apt and install Docker
        run: apt -y upgrade && apt -y install docker && apt -y install docker-compose
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Up docker-compose
        run: docker compose up
  
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Stopping docker compose
        run: sudo docker compose down
      - name: Rebuild docker compose images
        run: sudo docker compose up -d --build
        #tut klyuchi ssh nastraivayutsya
      