name: Depaloy app

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Upgrade apt and install Docker
        run: sudo apt -y upgrade && sudo apt -y install docker && sudo apt -y install docker-compose
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Up docker-compose
        run: sudo docker compose up
  
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Stopping docker compose
        run: docker compose down
      - name: Rebuild docker compose images
        run: docker compose up -d --build
      - run: cd ~/
      - run: git clone https://github.com/stefanprodan/dockprom
      - run: cd dockprom
      - run: docker-compose up -d
      